- name: Execute Script
  hosts: "{{ host_name }}"
  gather_facts: false
  remote_user: root
  tasks:
    - name: pip config file create
      file:
        path: "{{ dir }}/{{ pip_config_file }}"
        mode: "0444"
        state: touch
      register: script_file_created