- name: Execute Script
  hosts: "{{ host_name }}" # 你要在哪些机器上执行脚本
  gather_facts: false  # 关闭默认收集facts
  
  tasks:
    - name: Check if script file exists
      stat:
        path: "{{ script_file_path }}"
      register: script_file_stat
      failed_when: false  # 不将不存在的脚本文件视为失败

    - name: Check if script file is executable
      stat:
        path: "{{ script_file_path }}"
      register: script_executable_stat
      failed_when: false  # 不将不可执行的脚本文件视为失败

    - name: Copy script file
      copy:
        src: "{{ script_file_path }}"
        dest: "{{ target_script_path }}"
        mode: 0755
      when: script_file_stat.stat.exists and script_executable_stat.stat.mode|bool

    - name: Execute script
      shell: "{{ target_script_path }}"
      environment: "{{ environment_variables }}"
      register: script_result
      when: script_file_stat.stat.exists and script_executable_stat.stat.mode|bool


    - name: Return script output
      debug:
        var: script_result
