- name: Execute Script
  hosts: "{{ host_name }}" # 你要在哪些机器上执行脚本
  gather_facts: false  # 关闭默认收集facts
  remote_user: root
  
  tasks:
    - name: Copy script file
      copy:
        src: "{{ script_file_path }}"
        dest: "{{ target_script_path }}"
        owner: root
        group: root
        mode: 755


