- name: Execute Script
  hosts: "{{ host_name }}" # 你要在哪些机器上执行脚本
  gather_facts: false  # 关闭默认收集facts
  remote_user: root
  
  tasks:
    - name: Create shell script file
      file:
        path: /tmp/"{{ script_file_name}}"  # 目标脚本文件路径
        mode: "0755"  # 设置脚本文件的权限
        state: touch  # 创建空文件
      register: script_file_created

    - name: Add script content to file
      blockinfile:
        path: /path/to/your_script.sh  # 目标脚本文件路径
        content: |
          #!/bin/bash
          #INSTALL_WAZUH=true 
          set -ex
          
          sudo sed -i 's/http:\/\/archive.ubuntu.com/http:\/\/mirrors.cloud.tencent.com/g' /etc/apt/sources.list
          sudo sed -i 's/http:\/\/cn.archive.ubuntu.com/http:\/\/mirrors.cloud.tencent.com/g' /etc/apt/sources.list
          sudo sed -i 's/http:\/\/security.ubuntu.com/http:\/\/mirrors.cloud.tencent.com/g' /etc/apt/sources.list
          # sudo sed -i 's/deb.debian.org/mirrors.aliyun.com/g' /etc/apt/sources.list
          
          sudo apt-get update
          sudo apt-get dist-upgrade -yqq
          sudo apt-get install -y unzip curl htop iftop iotop ntp fail2ban jq nano man sysfsutils sudo tmux lvm2 gnupg2 sysfsutils
          
          # increase ulimit
          echo 'fs.file-max = 1000000' | sudo tee -a '/etc/sysctl.conf'
          echo 'vm.max_map_count = 262144' | sudo tee -a '/etc/sysctl.conf'
          sudo sysctl -p
          
          echo 'root soft nofile 1048576' | sudo tee -a '/etc/security/limits.conf'
          echo 'root hard nofile 1048576' | sudo tee -a '/etc/security/limits.conf'
          echo '* soft nofile 1048576' | sudo tee -a '/etc/security/limits.conf'
          echo '* hard nofile 1048576' | sudo tee -a '/etc/security/limits.conf'
          
          echo 'DefaultLimitNOFILE=1048576' | sudo tee -a '/etc/systemd/user.conf'
          echo 'DefaultLimitNOFILE=2097152' | sudo tee -a '/etc/systemd/system.conf'
          
          # disable THP
          echo 'kernel/mm/transparent_hugepage/enabled = never' | sudo tee -a '/etc/sysfs.conf'
          echo 'kernel/mm/transparent_hugepage/defrag = never' | sudo tee -a '/etc/sysfs.conf'
          
          systemctl enable fail2ban
          systemctl start fail2ban
          
          ## 这个后面要改成新的 wazuh 集群，后面在考虑
          
          # 检查是否执行安装 Wazuh 的步骤
          if [ $INSTALL_WAZUH = true ]; then
          	# 下载并安装 Wazuh Agent
          	HTTPS_PROXY=$HTTP_PROXY curl -so wazuh-agent.deb https://packages.wazuh.com/3.x/apt/pool/main/w/wazuh-agent/wazuh-agent_3.12.2-1_amd64.deb
          	sudo WAZUH_MANAGER='wazuh-manager.curiostack.com' dpkg -i ./wazuh-agent.deb
          fi

      when: script_file_created.changed

